USE[ConsoleShop];
INSERT INTO [dbo].[Category]([Name]) VALUES('Eat')
INSERT INTO [dbo].[Category]([Name]) VALUES('Toys')
INSERT INTO [dbo].[Category]([Name]) VALUES('ForPets')
INSERT INTO [dbo].[Category]([Name]) VALUES('Laptops')
INSERT INTO [dbo].[Category]([Name]) VALUES('Phones')
INSERT INTO [dbo].[Category]([Name]) VALUES('Plants')
INSERT INTO [dbo].[Category]([Name]) VALUES('ForSchool')
INSERT INTO [dbo].[Category]([Name]) VALUES('Cars')
INSERT INTO [dbo].[Category]([Name]) VALUES('Alcohol')

INSERT INTO [dbo].[Location]([Name]) VALUES('Авган')
INSERT INTO [dbo].[Location]([Name]) VALUES('Беларусь')
INSERT INTO [dbo].[Location]([Name]) VALUES('Чечня')
INSERT INTO [dbo].[Location]([Name]) VALUES('Канада')
INSERT INTO [dbo].[Location]([Name]) VALUES('Украина')
INSERT INTO [dbo].[Location]([Name]) VALUES('Литва')
INSERT INTO [dbo].[Location]([Name]) VALUES('Латвия')
INSERT INTO [dbo].[Location]([Name]) VALUES('Россия')

INSERT INTO [dbo].[ProductState]([State]) VALUES('New')
INSERT INTO [dbo].[ProductState]([State]) VALUES('Old')

INSERT INTO [dbo].[User]([Login],[Password],[Email],[PhoneNumber]) VALUES('VlastelinValentin','павук','pavyk@gmail.com','+365291725099')
INSERT INTO [dbo].[User]([Login],[Password],[Email],[PhoneNumber]) VALUES('Anatolya','123','pavyk@gmail.com','+365441365099')
INSERT INTO [dbo].[User]([Login],[Password],[Email],[PhoneNumber]) VALUES('Vadimka12','343221','vadimka@gmail.com','+3653317253467')
INSERT INTO [dbo].[User]([Login],[Password],[Email],[PhoneNumber]) VALUES('Valentinka48','345','valik@gmail.com','+365565625045')
INSERT INTO [dbo].[User]([Login],[Password],[Email],[PhoneNumber]) VALUES('Genka15','1234','genka@gmail.com','+365171479090')


INSERT INTO [dbo].[Product]([CategoryId],[LocationId],[StateId],[UserId],[Name],[Description],[Price])
VALUES(1,1,1,1,'СЯЛЕДКА','пожилая сельдь, с озер украины прямо к вам на стол',123)
INSERT INTO [dbo].[Product]([CategoryId],[LocationId],[StateId],[UserId],[Name],[Description],[Price])
VALUES(1,1,2,2,'name1','descr1',123)
INSERT INTO [dbo].[Product]([CategoryId],[LocationId],[StateId],[UserId],[Name],[Description],[Price])
VALUES(2,2,1,3,'name2','descr2',13)
INSERT INTO [dbo].[Product]([CategoryId],[LocationId],[StateId],[UserId],[Name],[Description],[Price])
VALUES(2,3,2,4,'name3','descr3',12)
INSERT INTO [dbo].[Product]([CategoryId],[LocationId],[StateId],[UserId],[Name],[Description],[Price])
VALUES(2,4,1,5,'name4','descr4',12)
INSERT INTO [dbo].[Product]([CategoryId],[LocationId],[StateId],[UserId],[Name],[Description],[Price])
VALUES(3,5,2,1,'name5','descr5',12)
