USE [ConsoleShop];
CREATE TABLE [dbo].[MainInfo]
(
[Id]INT IDENTITY(1,1) NOT NULL,
[Name]NVARCHAR(40) NOT NULL,
[Description]NVARCHAR(MAX) NOT NULL,
[Price]MONEY NOT NULL,
[DateOfCreation]NVARCHAR(40) NOT NULL,
[LastModifiedDate]NVARCHAR(40) NOT NULL,
PRIMARY KEY CLUSTERED([Id]ASC)
);
GO