USE [ConsoleShop];
CREATE TABLE [dbo].[Product]
(
	[Id]INT IDENTITY(1,1) NOT NULL,
	[Name]NVARCHAR(MAX) NOT NULL,
	[Description]NVARCHAR(MAX) NOT NULL,
	[Price]MONEY NOT NULL,
	[CreationDate]DATETIME NOT NULL,
	[LastModifiedDate]DATETIME NOT NULL,
	PRIMARY KEY CLUSTERED([Id]ASC)
);
GO